spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://********:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: **********
    password: ************
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true

logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-pro.log
server:
  port: 80



